### PR TITLE
Replaces invalid tag exception with logger warning

### PR DESCRIPTION
**Pull request by huettenhain**
This is my first attempt to contribute to #82; let me know if this works for you. Happy to change literally anything 🙂.

### CODE REVIEW

**Comment by huettenhain** [comment]
I have added all test cases that I found and wrote tests for them. All test cases are extracted by 7zip without any complaint, so I assume there must be some way to navigate them. I was able to relax a few exceptions to logger warnings, but some of the test cases are beyond my understanding of the library (and the ISO format) to fix.

**Review by clalancette — COMMENTED** [review]
First, thanks for the contribution.

I haven't done a detailed review of this yet, but a few things stood out to me at first glance:

1.  Let's not add these malware-laden ISOs here, I really don't want to distribute them.  See my comment in https://github.com/clalancette/pycdlib/issues/82#issuecomment-1079983885 for a way forward there instead.
2. There are too many changes in this one pull request.  It will be more work, but also a lot easier, to relax one thing at a time and add tests for that (this will also help with point 1).

**Comment by huettenhain** [comment]
Absolutely, I understand. I just had a free Sunday and wanted to get into the weeds a bit, maybe it's best to reject this PR. I am not sure I'll be able to construct the artificial test cases you desire 😅.

**Comment by clalancette** [comment]
> Absolutely, I understand. I just had a free Sunday and wanted to get into the weeds a bit, maybe it's best to reject this PR. I am not sure I'll be able to construct the artificial test cases you desire sweat_smile.

That's OK.  If you make some simpler PRs that just have individual changes that allow you to get further, we can evaluate them one-by-one and I can probably come up with some reasonable tests for them.

**Pull request closed without merging**
