### PR TITLE
Create .gitignore

### PR DESCRIPTION
**Pull request by rlaphoenix**
Common gitignore from GitHub's Python template.

### CODE REVIEW

**Comment by rlaPHOENiX** [comment]
You have `pycdlib.egg-info` in the git tree, which is typically purposefully ignored on VCS systems. Is there a particular reason you use it?

**Comment by clalancette** [comment]
> You have `pycdlib.egg-info` in the git tree, which is typically purposefully ignored on VCS systems. Is there a particular reason you use it?

Hm, are you sure about this?  I don't see that file committed anywhere.

**Comment by clalancette** [comment]
I'll be honest; I'm not a fan of `.gitignore` files (which is why there isn't one despite this project being ~6 years old).  I'd much rather see when I have things that aren't clean in my source repository.

I'll leave this open for now so you can comment, but I'm inclined not to take this PR.

**Comment by rlaPHOENiX** [comment]
That's fine if you don't want to, but its quite frustrating if you ever edit projects with any IDEs or have any Virtual env's in the directory, as git assumes you want to push the project settings and virtual env to the origin.

**Comment by rlaPHOENiX** [comment]
> 
> 
> > You have `pycdlib.egg-info` in the git tree, which is typically purposefully ignored on VCS systems. Is there a particular reason you use it?
> 
> Hm, are you sure about this? I don't see that file committed anywhere.

I could have sworn it was there, apologies.

**Comment by clalancette** [comment]
I'm going to close this out, since I'm just not a fan of `.gitignore`.  Thanks anyway for the contribution!

**Pull request closed without merging**
